x-custom-image: &frappe_image
  image: ${IMAGE_NAME:-docker.io/frappe/erpnext}:${VERSION:-version-15}
  pull_policy: ${PULL_POLICY:-if_not_present}

services:

  backend:
    <<: *frappe_image
    command: bench start
    volumes:
      - sites:/home/frappe/frappe-bench/sites
    networks:
      - bench-network
    environment:
      - REDIS_CACHE=redis-cache:6379
      - REDIS_QUEUE=redis-queue:6379
      - REDIS_SOCKETIO=redis-socketio:6379
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 10s
      timeout: 10s
      retries: 10

  frontend:
    <<: *frappe_image
    command: nginx-entrypoint.sh
    ports:
      - "8082:8080"
    environment:
      BACKEND: backend:8000
      SOCKETIO: websocket:9000
      FRAPPE_SITE_NAME_HEADER: ${FRAPPE_SITE_NAME_HEADER:-$host}
      UPSTREAM_REAL_IP_ADDRESS: 0.0.0.0/0
      UPSTREAM_REAL_IP_HEADER: X-Forwarded-For
      UPSTREAM_REAL_IP_RECURSIVE: "off"
    volumes:
      - sites:/home/frappe/frappe-bench/sites
    depends_on:
      - backend
      - websocket
    networks:
      - bench-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 10s
      timeout: 20s
      retries: 10

  websocket:
    <<: *frappe_image
    command: node /home/frappe/frappe-bench/apps/frappe/socketio.js
    volumes:
      - sites:/home/frappe/frappe-bench/sites
    networks:
      - bench-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000"]
      interval: 10s
      timeout: 10s
      retries: 10

  queue-default:
    <<: *frappe_image
    command: bench worker --queue default
    volumes:
      - sites:/home/frappe/frappe-bench/sites
    networks:
      - bench-network

  queue-long:
    <<: *frappe_image
    command: bench worker --queue long
    volumes:
      - sites:/home/frappe/frappe-bench/sites
    networks:
      - bench-network

  queue-short:
    <<: *frappe_image
    command: bench worker --queue short
    volumes:
      - sites:/home/frappe/frappe-bench/sites
    networks:
      - bench-network

  scheduler:
    <<: *frappe_image
    command: bench schedule
    volumes:
      - sites:/home/frappe/frappe-bench/sites
    networks:
      - bench-network

  configurator:
    <<: *frappe_image
    entrypoint: ["bash", "-c"]
    command: >
      bench set-config -g db_host $DB_HOST;
      bench set-config -g db_port $DB_PORT;
      bench set-config -g redis_cache redis://$REDIS_CACHE;
      bench set-config -g redis_queue redis://$REDIS_QUEUE;
      bench set-config -g redis_socketio redis://$REDIS_SOCKETIO;
    environment:
      DB_HOST: ${DB_HOST:-db}
      DB_PORT: 3306
      REDIS_CACHE: redis-cache:6379
      REDIS_QUEUE: redis-queue:6379
      REDIS_SOCKETIO: redis-socketio:6379
    volumes:
      - sites:/home/frappe/frappe-bench/sites
    networks:
      - bench-network

  create-site:
    <<: *frappe_image
    entrypoint: ["bash", "-c"]
    command: >
      wait-for-it $DB_HOST:$DB_PORT -t 120;
      bench new-site --mariadb-user-host-login-scope='%' 
      --admin-password=$ADMIN_PASSWORD 
      --db-root-username=root 
      --db-root-password=$DB_ROOT_PASSWORD 
      $SITE_NAME || true;
    environment:
      SITE_NAME: ${SITE_NAME}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      DB_HOST: ${DB_HOST:-db}
      DB_PORT: ${DB_PORT:-3306}
      DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - sites:/home/frappe/frappe-bench/sites
    networks:
      - bench-network

  migration:
    <<: *frappe_image
    entrypoint: ["bash", "-c"]
    command: >
      bench --site all migrate;
      bench --site all set-config -p maintenance_mode 0;
      bench --site all set-config -p pause_scheduler 0;
    volumes:
      - sites:/home/frappe/frappe-bench/sites
    networks:
      - bench-network

  db:
    image: mariadb:10.6
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - bench-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p${DB_ROOT_PASSWORD}"]
      interval: 10s
      retries: 10

  redis-cache:
    image: redis:6.2-alpine
    volumes:
      - redis-cache-data:/data
    networks:
      - bench-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 5

  redis-queue:
    image: redis:6.2-alpine
    volumes:
      - redis-queue-data:/data
    networks:
      - bench-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 5

  redis-socketio:
    image: redis:6.2-alpine
    volumes:
      - redis-socketio-data:/data
    networks:
      - bench-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 5

volumes:
  db-data:
  redis-cache-data:
  redis-queue-data:
  redis-socketio-data:
  sites:

networks:
  bench-network: